### ISSUE TITLE
node-canvas dependency breaks browserify

### ISSUE THREAD

**Issue by chrishoage** [neocotic/qrious#28]
I am trying to use this library in a browserify project, which won't need node-canvas. 

Is there any way the node-canvas dependency be changed so that it is not required when npm installing? 

Maybe using optionalDependencies in package.json?

**Comment by neocotic** [comment]
This should hopefully be fixed once I finally get around to testing and merging PR #26 but I believe [there are ways of telling browserify to ignore modules](https://github.com/substack/browserify-handbook/blob/master/readme.markdown#ignoring-and-excluding), although I'm not sure how well that works since I'm not too familiar with the tool.

**Comment by chrishoage** [comment]
Thank you for the response, that is great to hear. I actually forked your repo last night after posting this and made it work using browserify "specific" npm modules for the fs and canvas requires. 

https://github.com/chrishoage/qr.js

I can submit a pull request if you'd like but it sounds like this is close to be supported via an alternate method.

**Comment by bstro** [comment]
With browserify, I am getting
```
ERROR in ./~/canvas/lib/bindings.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/canvas in ../node_modules/canvas/lib
 @ ./~/canvas/lib/bindings.js 2:17-51
```
even with @chrishoage 's fork. Is this related?

**Comment by neocotic** [comment]
Again, I'm not familiar with Browserify so I couldn't say but I am keen to support it as I like it's goal. I'm curious if anyone else could help with this.

When exactly are you getting this error? During build, runtime, from Browserify?

Have you tried the "ignore" option that I suggested?

**Comment by theefer** [comment]
FYI I tried passing `--ignore canvas` and that fixed the compilation error.

**Comment by jedierikb** [comment]
was unable to work your pretty great looking library into my project because of this issue + deadlines :-(

**Comment by olso** [comment]
Is this being worked on?

**Comment by neocotic** [comment]
@olso I'm currently playing around with a significant rewrite of this library that I'm hoping will make it more portable across different environments (e.g. browser, node.js). I'm hoping to have that wrapped up within a week or two, but please feel free to bug me for an update if I don't give one in case I forget.

**Comment by olso** [comment]
@neocotic how is it going? 🎱

**Comment by neocotic** [comment]
Unfortunately, I've been a bit too busy juggling other projects and work this last month, but I promise you that this is still on my radar. Not much is left to do but I'm trying to make sure that this solves the problem in the right way.

The new approach also uses Babel so that I can structure the code better (initially, it will simply be separated better and will refactor to be better in the future) so I also need to make sure that I'm not bloating the library unnecessarily as a result.

**Comment by neocotic** [comment]
I'm really hoping that is taken care of now in v2 (aka QRious #48) as I've tried to make the support for multiple different package managers.

Sorry for taking so long to reply to this and thanks for using this library. I hope you find the the newer version easier to use and better.

I'm going to mark this as closed now as `package.json` now has a `browser` field that it should pick up. `canvas` is now down as an `optionalDependency` so the install will no longer fail cairo is not installed.

If you have any problems in the future with this support, please raise a separate issue.

**Comment by justin-lau** [comment]
The `package.json` of v2.2 on the npm registry still has `canvas` in the `dependencies` on top of `optionalDependencies`, resulting in the same error.

**Comment by neocotic** [comment]
@justin-lau You're right! How strange. I've no idea why it's doing that since the `package.json` in master does not contain it. I might try simply doing a version bump and see if that fixes it. Good spot. I'll raise a separate bug for this.
