### ISSUE TITLE
Save does not support colors

### ISSUE THREAD

**Issue by thasmo** [neocotic/qrious#31]
It would be nice if using the save function also supports background and foreground colors.

**Comment by neocotic** [comment]
Closing this as a duplicate of #2.

Open to pull requests for this issue as is love to see it fixed but struggling to find the time.

**Comment by neocotic** [comment]
Sorry, closed the wrong issue.

**Comment by neocotic** [comment]
The `save` and `saveSync` methods have been removed in v2 (aka QRious) since they are out-of-scope for this library, so I'm closing this issue and marking it as invalid.

Sorry for taking so long to reply to this and thanks for using this library. I hope you find the the newer version easier to use and better.
