### ISSUE TITLE
webpack issue with canvas

### ISSUE THREAD

**Issue by emmanuelgeoffray** [neocotic/qrious#51]
Hey there,
Thank you for your efforts on the new version 2.0.1 !
Do you have a working example of using webpack?
I tried to use `npm install --no-optional` 
but I still get an error when running webpack
```ERROR in ./~/qrious/dist/cjs/qrious.js
Module not found: Error: Cannot resolve module 'canvas' in my/path/to/node_modules/qrious/dist/cjs
 @ ./~/qrious/dist/cjs/qrious.js 23:13-30```
```

Did you encounter the same issue before?

Thanks!
& have a great day,
Emmanuel

**Comment by neocotic** [comment]
I'll be honest, I worked purely based on assumption with that regard as I haven't really dealt with these kinds of details with Webpack.

Due to the complex nature of our dependency on `node-canvas`, I'm currently considering splitting this project into 3 modules: one containing the core code, one for browser, and one for node. This would be a breaking change so would require a major version bump, but should help keep dependencies and dependencies much simpler.

Thanks for bringing this to my attention. Once I've

**Comment by leeyeh** [comment]
https://github.com/leeyeh/qrious-webpack-demo
https://rawgit.com/leeyeh/qrious-webpack-demo/master/index.html

**Comment by neocotic** [comment]
@emmanuelgeoffray, can you please check the demo provided by @leeyeh and confirm whether you're still seeing this problem? I'd recommend upgrading to 2.0.2 as well as this fixes an issue with QR code generation.

**Comment by neocotic** [comment]
Closing this out as not heard back from reporter but will reopen if a simple project can be created to reproduce this issue.
