### ISSUE TITLE
Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by zucker-rdrg** [neocotic/qrious#55]
Cannot use qrious in IE or Safari <= 8
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

**Comment by neocotic** [comment]
Good spot! I was under the impression that Babel replaced such code. I'll take a look at this.

**Comment by neocotic** [comment]
I just wanted to provide an update on this as I've not done so for a while.

It would seem that, in order to get this working with the current system, I'll have to include the babel-runtime transformers inside of QRious. This isn't too tricky to do, however, it comes at a cost. Doing so will no doubt add a big bloat (~20KB) to the minified code base. I'm going to look into ways of minimizing this and possible alternatives such as not using ES6+Babel (another rewrite :cry:).

I'm tempted to take a staged approach to this:

1. Fix bug by including babel-runtime transformers
2. Try to minimize bloat using whatever means possible

**Comment by neocotic** [comment]
This issue should be fixed in the just-released version 2.1.0 of QRious.

Please try upgrading and let me know how you get on.

As a result of the fix, `babel-runtime` has been bundled in our distribution files. Unfortunately, this has added some bloat to the size of our files so I've raised #59 which will attempt to investigate and address this.

**Comment by zucker-rdrg** [comment]
Hi,
I've checked this on IE 10 and it works :)

Thank you
