### ISSUE TITLE
Remove padding

### ISSUE THREAD

**Issue by mscreenie** [neocotic/qrious#60]
If I set padding to 0 the qr code acts generates an image with white space to the right, this happens by generating a dataurl directly without a element. The 

I am Just trying to remove padding completely.

Great work btw it's quite fast compared to other ones I have used.

**Comment by neocotic** [comment]
@mscreenie, the new padding feature isn't perfect, which is why I was originally reluctant to implement it. When nulled the padding will be determined automatically based on a number of variables. However, due to the nature of QR codes things like the complexity of the data being encoded can cause the QR size to change and other things like the element size can impact the module widths and therefore the dimensions in needed in order to fit into the element. There's only so many modules you can fit into an image before it needs to grow.

Please feel free to take a look at the code to see if you could improve the padding feature; which was only just added in the last release. I'm open to pull requests :smile:

You might want to try playing around with giving your QR code different fixed sizes with 0 padding. However, if the data encoded data is dynamic at all, it the size QR code could change if the data is large enough and therefore your workaround might not work in all cases.

**Comment by mscreenie** [comment]
Thanks. Just read my original post. I must have been daydreaming.  I'll try setting padding to zero but if I vaguely remember it produced the same error.

**Comment by giiska** [comment]
Why wont fix? I need padding 0

**Comment by buggy-95** [comment]
My project need no padding, too
